### ISSUE TITLE
Winnow query limit check does not work for pass-thru providers

### ISSUE THREAD

**Issue by jkerr5** [koopjs/koop#306]
When a client is paginating through features from a pass-thru provider, winnow throws this error:

```javascript
Trace: Error: OFFSET >= features length: [object Object]
    at limitQuery (/koop-provider-marklogic/node_modules/winnow/dist/executeQuery.js:36:52)
    at Object.Winnow.query (/koop-provider-marklogic/node_modules/winnow/dist/index.js:34:36)
    at query (/koop-provider-marklogic/node_modules/featureserver/dist/query.js:28:28)
    at execQuery (/koop-provider-marklogic/node_modules/featureserver/dist/route.js:43:16)
    at Object.route (/koop-provider-marklogic/node_modules/featureserver/dist/route.js:32:14)
    at /koop-provider-marklogic/node_modules/koop-output-geoservices/index.js:9:24
    at /koop-provider-marklogic/node_modules/koop/dist/models/index.js:15:9
    at mq.providerGetData.then.data (/koop-provider-marklogic/marklogic.js:40:8)
    at execQuery (/koop-provider-marklogic/node_modules/featureserver/dist/route.js:45:52)
    at Object.route (/koop-provider-marklogic/node_modules/featureserver/dist/route.js:32:14)
    at /koop-provider-marklogic/node_modules/koop-output-geoservices/index.js:9:24
    at /koop-provider-marklogic/node_modules/koop/dist/models/index.js:15:9
    at mq.providerGetData.then.data (/koop-provider-marklogic/marklogic.js:40:8)
```
For a pass-thru provider, winnow should probably not be used to process the offset and limit options.

**Comment by dmfenton** [comment]
there is now `metadata.filtersApplied.offset` set that and FeatureServer will delete this parameter before it gets to Winnow
